/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        neon: { green: "#00FF94", purple: "#8B5CF6", cyan: "#00D9FF", magenta: "#A855F7" },
        void: { DEFAULT: "#000000", deep: "#050505", panel: "#0a0a0a", elevated: "#111111" },
        pirate: { gold: "#F59E0B", blood: "#EF4444", rum: "#78350F" },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: { xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)" },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "caret-blink": { "0%,70%,100%": { opacity: "1" }, "20%,50%": { opacity: "0" } },
        "aurora-green": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
        },
        "aurora-purple": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(-30px, 50px) scale(1.1)" },
          "66%": { transform: "translate(20px, -20px) scale(0.9)" },
        },
        "grid-flow": {
          "0%": { transform: "rotateX(60deg) translateY(0)" },
          "100%": { transform: "rotateX(60deg) translateY(60px)" },
        },
        "float": { "0%, 100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-20px)" } },
        "glitch": {
          "0%, 100%": { transform: "translate(0)" },
          "20%": { transform: "translate(-2px, 2px)" },
          "40%": { transform: "translate(-2px, -2px)" },
          "60%": { transform: "translate(2px, 2px)" },
          "80%": { transform: "translate(2px, -2px)" },
        },
        "scan": { "0%": { transform: "translateY(-100%)" }, "100%": { transform: "translateY(100%)" } },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.05)" },
        },
        "marquee-scroll": { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        "cube-rotate": { "0%": { transform: "rotateX(-20deg) rotateY(0deg)" }, "100%": { transform: "rotateX(-20deg) rotateY(360deg)" } },
        "scroll-bounce": { "0%, 100%": { transform: "translateY(0)", opacity: "1" }, "50%": { transform: "translateY(8px)", opacity: "0.5" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "aurora-green": "aurora-green 14s ease-in-out infinite",
        "aurora-purple": "aurora-purple 18s ease-in-out infinite",
        "grid-flow": "grid-flow 10s linear infinite",
        "float": "float 6s ease-in-out infinite",
        "glitch": "glitch 0.3s ease-in-out",
        "scan": "scan 4s linear infinite",
        "pulse-glow": "pulse-glow 4s ease-in-out infinite",
        "marquee-scroll": "marquee-scroll 40s linear infinite",
        "cube-rotate": "cube-rotate 3s linear infinite",
        "scroll-bounce": "scroll-bounce 2s ease-in-out infinite",
      },
      backgroundImage: {
        "cyber-gradient": "linear-gradient(135deg, rgba(0,255,148,0.15) 0%, rgba(139,92,246,0.15) 100%)",
        "plunder-gradient": "linear-gradient(90deg, #00FF94 0%, #8B5CF6 100%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};